### ISSUE TITLE
Current GH action does not create issues in Github

### ISSUE THREAD

**Issue by juegge** [Checkmarx/kics-github-action#17]
Current GH action (1.2) is not creating issues in Github. 
Workflows using the current GH action fail afyter KICS scan.
This is due to a missing log file and might be related to an issue with KICS reported here:
https://github.com/Checkmarx/kics/issues/3141#issue-878091893

**Comment by joaoReigota1** [comment]
Hello @juegge, thank you for the report and sorry for the late response,
Regarding the issues, KICS Github Actions doesn't create issues in Github. Since version 1.3 it will comment on your PR informing you of the vulnerabilities found and give annotations on the files containing them as you can see [here](https://github.com/Checkmarx/kics-github-action#pr-comment-example)  
The missing log bug I believe it was fixed in version 1.3 as well
